name: Build executables and publish 📦 to PyPI

on:
  workflow_dispatch:
  release:
    types:
      - "published"

jobs:
  wheel:
    name: Package 📦 wheel
    runs-on: ubuntu-latest
    steps:

    - name: Clone repo
      uses: actions/checkout@v3

    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: "3.8.x"

    - name: Install pypa/build
      run: >-
        python -m
        pip install
        build
        --user
        
    - name: Build a binary wheel and a source tarball
      run: >-
        python -m
        build
        --sdist
        --wheel
        --outdir dist/

    - name: Publish distribution 📦 to PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
